import { Jost, Roboto } from "next/font/google";
import "./css/globals.scss";

const jost = Jost({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Kugoo next app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={jost.className}>{children}</body>
    </html>
  );
}
